apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd2
spec:
  destination:
    namespace: argocd2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ch03/kustomize-installation
    repoURL: https://github.com/PacktPublishing/ArgoCD-in-Practice.git
    targetRevision: main
  syncPolicy:
    automated: {}
