apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd2
spec:
  destination:
    namespace: argocd2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd
    repoURL: https://github.com/alvarocperez/argo-kustomize.git
    targetRevision: master
  syncPolicy:
    automated: {}
